import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BackgroundLines } from "@/components/ui/background-lines";
import  "./globals.css";
import Navbar  from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mirha App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="light
    ">
      <body className={inter.className} >
        <Navbar/>
        
        {children}
        <Toaster />
      
        <Footer/>
        
        </body>
    </html>
  );
}
